/*
 * This file is generated by jOOQ.
 */
package jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.tables.Deck;
import jooq.tables.Id;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScpTcg extends SchemaImpl {

    private static final long serialVersionUID = 724545757;

    /**
     * The reference instance of <code>scp_tcg</code>
     */
    public static final ScpTcg SCP_TCG = new ScpTcg();

    /**
     * The table <code>scp_tcg.deck</code>.
     */
    public final Deck DECK = jooq.tables.Deck.DECK;

    /**
     * The table <code>scp_tcg.id</code>.
     */
    public final Id ID = jooq.tables.Id.ID;

    /**
     * No further instances allowed
     */
    private ScpTcg() {
        super("scp_tcg", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Deck.DECK,
            Id.ID);
    }
}
