/*
 * This file is generated by jOOQ.
 */
package jooq;


import javax.annotation.Generated;

import jooq.tables.Deck;
import jooq.tables.Id;


/**
 * Convenience access to all tables in scp_tcg
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>scp_tcg.deck</code>.
     */
    public static final Deck DECK = jooq.tables.Deck.DECK;

    /**
     * The table <code>scp_tcg.id</code>.
     */
    public static final Id ID = jooq.tables.Id.ID;
}
