/*
 * This file is generated by jOOQ.
 */
package jooq.sakila;


import jooq.sakila.tables.*;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in sakila
 */
@Generated(
    value = {
        "http://www.jooq.org",
            "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>sakila.actor</code>.
     */
    public static final Actor ACTOR = jooq.sakila.tables.Actor.ACTOR;

    /**
     * VIEW
     */
    public static final ActorInfo ACTOR_INFO = jooq.sakila.tables.ActorInfo.ACTOR_INFO;

    /**
     * The table <code>sakila.address</code>.
     */
    public static final Address ADDRESS = jooq.sakila.tables.Address.ADDRESS;

    /**
     * The table <code>sakila.category</code>.
     */
    public static final Category CATEGORY = jooq.sakila.tables.Category.CATEGORY;

    /**
     * The table <code>sakila.city</code>.
     */
    public static final City CITY = jooq.sakila.tables.City.CITY;

    /**
     * The table <code>sakila.country</code>.
     */
    public static final Country COUNTRY = jooq.sakila.tables.Country.COUNTRY;

    /**
     * The table <code>sakila.customer</code>.
     */
    public static final Customer CUSTOMER = jooq.sakila.tables.Customer.CUSTOMER;

    /**
     * VIEW
     */
    public static final CustomerList CUSTOMER_LIST = jooq.sakila.tables.CustomerList.CUSTOMER_LIST;

    /**
     * The table <code>sakila.film</code>.
     */
    public static final Film FILM = jooq.sakila.tables.Film.FILM;

    /**
     * The table <code>sakila.film_actor</code>.
     */
    public static final FilmActor FILM_ACTOR = jooq.sakila.tables.FilmActor.FILM_ACTOR;

    /**
     * The table <code>sakila.film_category</code>.
     */
    public static final FilmCategory FILM_CATEGORY = jooq.sakila.tables.FilmCategory.FILM_CATEGORY;

    /**
     * VIEW
     */
    public static final FilmList FILM_LIST = jooq.sakila.tables.FilmList.FILM_LIST;

    /**
     * The table <code>sakila.film_text</code>.
     */
    public static final FilmText FILM_TEXT = jooq.sakila.tables.FilmText.FILM_TEXT;

    /**
     * The table <code>sakila.inventory</code>.
     */
    public static final Inventory INVENTORY = jooq.sakila.tables.Inventory.INVENTORY;

    /**
     * The table <code>sakila.language</code>.
     */
    public static final Language LANGUAGE = jooq.sakila.tables.Language.LANGUAGE;

    /**
     * VIEW
     */
    public static final NicerButSlowerFilmList NICER_BUT_SLOWER_FILM_LIST = jooq.sakila.tables.NicerButSlowerFilmList.NICER_BUT_SLOWER_FILM_LIST;

    /**
     * The table <code>sakila.payment</code>.
     */
    public static final Payment PAYMENT = jooq.sakila.tables.Payment.PAYMENT;

    /**
     * The table <code>sakila.rental</code>.
     */
    public static final Rental RENTAL = jooq.sakila.tables.Rental.RENTAL;

    /**
     * VIEW
     */
    public static final SalesByFilmCategory SALES_BY_FILM_CATEGORY = jooq.sakila.tables.SalesByFilmCategory.SALES_BY_FILM_CATEGORY;

    /**
     * VIEW
     */
    public static final SalesByStore SALES_BY_STORE = jooq.sakila.tables.SalesByStore.SALES_BY_STORE;

    /**
     * The table <code>sakila.staff</code>.
     */
    public static final Staff STAFF = jooq.sakila.tables.Staff.STAFF;

    /**
     * VIEW
     */
    public static final StaffList STAFF_LIST = jooq.sakila.tables.StaffList.STAFF_LIST;

    /**
     * The table <code>sakila.store</code>.
     */
    public static final Store STORE = jooq.sakila.tables.Store.STORE;
}
