/*
 * This file is generated by jOOQ.
 */
package jooq.sys.routines;


import jooq.sys.Sys;
import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;

import javax.annotation.Generated;


/**
 * Description
 * <p>
 * Takes a list, and a value to add to the list, and returns the resulting
 * list.
 * <p>
 * Useful for altering certain session variables, like sql_mode or optimizer_switch
 * for instance.
 * <p>
 * Parameters
 * <p>
 * in_list (TEXT):
 * The comma separated list to add a value to
 * <p>
 * in_add_value (TEXT):
 * The value to add to the input list
 * <p>
 * Returns
 * <p>
 * TEXT
 * <p>
 * Example
 * <p>
 * mysql&gt; select @@sql_mode;
 * +-----------------------------------------------------------------------------------+
 * | @@sql_mode
 * |
 * +-----------------------------------------------------------------------------------+
 * | ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
 * |
 * +-----------------------------------------------------------------------------------+
 * 1 row in set (0.00 sec)
 * <p>
 * mysql&gt; set sql_mode = sys.list_add(@@sql_mode, 'ANSI_QUOTES');
 * Query OK, 0 rows affected (0.06 sec)
 * <p>
 * mysql&gt; select @@sql_mode;
 * +-----------------------------------------------------------------------------------------------+
 * | @@sql_mode
 * |
 * +-----------------------------------------------------------------------------------------------+
 * | ANSI_QUOTES,ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
 * |
 * +-----------------------------------------------------------------------------------------------+
 * 1 row in set (0.00 sec)
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.2"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ListAdd extends AbstractRoutine<String> {

    /**
     * The parameter <code>sys.list_add.RETURN_VALUE</code>.
     */
    public static final Parameter<String> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.CLOB, false, false);
    /**
     * The parameter <code>sys.list_add.in_list</code>.
     */
    public static final Parameter<String> IN_LIST = createParameter("in_list", org.jooq.impl.SQLDataType.CLOB, false, false);
    /**
     * The parameter <code>sys.list_add.in_add_value</code>.
     */
    public static final Parameter<String> IN_ADD_VALUE = createParameter("in_add_value", org.jooq.impl.SQLDataType.CLOB, false, false);
    private static final long serialVersionUID = -987189518;

    /**
     * Create a new routine call instance
     */
    public ListAdd() {
        super("list_add", Sys.SYS, org.jooq.impl.SQLDataType.CLOB);

        setReturnParameter(RETURN_VALUE);
        addInParameter(IN_LIST);
        addInParameter(IN_ADD_VALUE);
    }

    /**
     * Set the <code>in_list</code> parameter IN value to the routine
     */
    public void setInList(String value) {
        setValue(IN_LIST, value);
    }

    /**
     * Set the <code>in_list</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setInList(Field<String> field) {
        setField(IN_LIST, field);
    }

    /**
     * Set the <code>in_add_value</code> parameter IN value to the routine
     */
    public void setInAddValue(String value) {
        setValue(IN_ADD_VALUE, value);
    }

    /**
     * Set the <code>in_add_value</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setInAddValue(Field<String> field) {
        setField(IN_ADD_VALUE, field);
    }
}
