/*
 * This file is generated by jOOQ.
 */
package jooq.sys.routines;


import jooq.sys.Sys;
import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * 
 *  Description
 *  
 *  Determines whether a consumer is enabled (taking the consumer hierarchy 
 * into consideration)
 *  within the Performance Schema.
 *  
 *  Parameters
 *  
 *  in_consumer VARCHAR(64): 
 *  The name of the consumer to check.
 *  
 *  Returns
 *  
 *  ENUM('YES', 'NO')
 *  
 *  Example
 *  
 *  mysql&gt; SELECT sys.ps_is_consumer_enabled('events_stages_history');
 *  +-----------------------------------------------------+
 *  | sys.ps_is_consumer_enabled('events_stages_history') |
 *  +-----------------------------------------------------+
 *  | NO                                                  |
 *  +-----------------------------------------------------+
 *  1 row in set (0.00 sec)
 *  
 */
@Generated(
    value = {
        "http://www.jooq.org",
            "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PsIsConsumerEnabled extends AbstractRoutine<String> {

    private static final long serialVersionUID = 1547989316;

    /**
     * The parameter <code>sys.ps_is_consumer_enabled.RETURN_VALUE</code>.
     */
    public static final Parameter<String> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.VARCHAR(3), false, false);

    /**
     * The parameter <code>sys.ps_is_consumer_enabled.in_consumer</code>.
     */
    public static final Parameter<String> IN_CONSUMER = Internal.createParameter("in_consumer", org.jooq.impl.SQLDataType.VARCHAR(64), false, false);

    /**
     * Create a new routine call instance
     */
    public PsIsConsumerEnabled() {
        super("ps_is_consumer_enabled", Sys.SYS, org.jooq.impl.SQLDataType.VARCHAR(3));

        setReturnParameter(RETURN_VALUE);
        addInParameter(IN_CONSUMER);
    }

    /**
     * Set the <code>in_consumer</code> parameter IN value to the routine
     */
    public void setInConsumer(String value) {
        setValue(IN_CONSUMER, value);
    }

    /**
     * Set the <code>in_consumer</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setInConsumer(Field<String> field) {
        setField(IN_CONSUMER, field);
    }
}
