/*
 * This file is generated by jOOQ.
 */
package jooq.sys.routines;


import jooq.sys.Sys;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;

import javax.annotation.Generated;


/**
 * Description
 * <p>
 * Enables consumers within Performance Schema
 * matching the input pattern.
 * <p>
 * Parameters
 * <p>
 * consumer (VARCHAR(128)):
 * A LIKE pattern match (using "%consumer%") of consumers to enable
 * <p>
 * Example
 * <p>
 * To enable all consumers:
 * <p>
 * mysql&gt; CALL sys.ps_setup_enable_consumer('');
 * +-------------------------+
 * | summary                 |
 * +-------------------------+
 * | Enabled 10 consumers    |
 * +-------------------------+
 * 1 row in set (0.02 sec)
 * <p>
 * Query OK, 0 rows affected (0.02 sec)
 * <p>
 * To enable just "waits" consumers:
 * <p>
 * mysql&gt; CALL sys.ps_setup_enable_consumer('waits');
 * +-----------------------+
 * | summary               |
 * +-----------------------+
 * | Enabled 3 consumers   |
 * +-----------------------+
 * 1 row in set (0.00 sec)
 * <p>
 * Query OK, 0 rows affected (0.00 sec)
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.2"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PsSetupEnableConsumer extends AbstractRoutine<java.lang.Void> {

    /**
     * The parameter <code>sys.ps_setup_enable_consumer.consumer</code>.
     */
    public static final Parameter<String> CONSUMER = createParameter("consumer", org.jooq.impl.SQLDataType.VARCHAR(128), false, false);
    private static final long serialVersionUID = -472608115;

    /**
     * Create a new routine call instance
     */
    public PsSetupEnableConsumer() {
        super("ps_setup_enable_consumer", Sys.SYS);

        addInParameter(CONSUMER);
    }

    /**
     * Set the <code>consumer</code> parameter IN value to the routine
     */
    public void setConsumer(String value) {
        setValue(CONSUMER, value);
    }
}
