/*
 * This file is generated by jOOQ.
 */
package jooq.sys.routines;


import jooq.sys.Sys;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;

import javax.annotation.Generated;


/**
 * Description
 * <p>
 * Enable the given connection/thread in Performance Schema.
 * <p>
 * Parameters
 * <p>
 * in_connection_id (BIGINT):
 * The connection ID (PROCESSLIST_ID from performance_schema.threads
 * or the ID shown within SHOW PROCESSLIST)
 * <p>
 * Example
 * <p>
 * mysql&gt; CALL sys.ps_setup_enable_thread(3);
 * +------------------+
 * | summary          |
 * +------------------+
 * | Enabled 1 thread |
 * +------------------+
 * 1 row in set (0.01 sec)
 * <p>
 * To enable the current connection:
 * <p>
 * mysql&gt; CALL sys.ps_setup_enable_thread(CONNECTION_ID());
 * +------------------+
 * | summary          |
 * +------------------+
 * | Enabled 1 thread |
 * +------------------+
 * 1 row in set (0.00 sec)
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.2"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PsSetupEnableThread extends AbstractRoutine<java.lang.Void> {

    /**
     * The parameter <code>sys.ps_setup_enable_thread.in_connection_id</code>.
     */
    public static final Parameter<Long> IN_CONNECTION_ID = createParameter("in_connection_id", org.jooq.impl.SQLDataType.BIGINT, false, false);
    private static final long serialVersionUID = -1432789212;

    /**
     * Create a new routine call instance
     */
    public PsSetupEnableThread() {
        super("ps_setup_enable_thread", Sys.SYS);

        addInParameter(IN_CONNECTION_ID);
    }

    /**
     * Set the <code>in_connection_id</code> parameter IN value to the routine
     */
    public void setInConnectionId(Long value) {
        setValue(IN_CONNECTION_ID, value);
    }
}
