/*
 * This file is generated by jOOQ.
 */
package jooq.sys.routines;


import jooq.sys.Sys;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * 
 *  Description
 *  
 *  Disable the given connection/thread in Performance Schema.
 *  
 *  Parameters
 *  
 *  in_connection_id (BIGINT):
 *  The connection ID (PROCESSLIST_ID from performance_schema.threads
 *  or the ID shown within SHOW PROCESSLIST)
 *  
 *  Example
 *  
 *  mysql&gt; CALL sys.ps_setup_disable_thread(3);
 *  +-------------------+
 *  | summary           |
 *  +-------------------+
 *  | Disabled 1 thread |
 *  +-------------------+
 *  1 row in set (0.01 sec)
 *  
 *  To disable the current connection:
 *  
 *  mysql&gt; CALL sys.ps_setup_disable_thread(CONNECTION_ID());
 *  +-------------------+
 *  | summary           |
 *  +-------------------+
 *  | Disabled 1 thread |
 *  +-------------------+
 *  1 row in set (0.00 sec)
 *  
 */
@Generated(
    value = {
        "http://www.jooq.org",
            "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PsSetupDisableThread extends AbstractRoutine<java.lang.Void> {

    /**
     * The parameter <code>sys.ps_setup_disable_thread.in_connection_id</code>.
     */
    public static final Parameter<Long> IN_CONNECTION_ID = Internal.createParameter("in_connection_id", org.jooq.impl.SQLDataType.BIGINT, false, false);
    private static final long serialVersionUID = 1938445752;

    /**
     * Create a new routine call instance
     */
    public PsSetupDisableThread() {
        super("ps_setup_disable_thread", Sys.SYS);

        addInParameter(IN_CONNECTION_ID);
    }

    /**
     * Set the <code>in_connection_id</code> parameter IN value to the routine
     */
    public void setInConnectionId(Long value) {
        setValue(IN_CONNECTION_ID, value);
    }
}
