/*
 * This file is generated by jOOQ.
 */
package jooq.sys.routines;


import jooq.sys.Sys;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;

import javax.annotation.Generated;


/**
 * Description
 * <p>
 * Saves the current configuration of Performance Schema,
 * so that you can alter the setup for debugging purposes,
 * but restore it to a previous state.
 * <p>
 * Use the companion procedure - ps_setup_reload_saved(), to
 * restore the saved config.
 * <p>
 * The named lock "sys.ps_setup_save" is taken before the
 * current configuration is saved. If the attempt to get the named
 * lock times out, an error occurs.
 * <p>
 * The lock is released after the settings have been restored by
 * calling ps_setup_reload_saved().
 * <p>
 * Requires the SUPER privilege for "SET sql_log_bin = 0;".
 * <p>
 * Parameters
 * <p>
 * in_timeout INT
 * The timeout in seconds used when trying to obtain the lock.
 * A negative timeout means infinite timeout.
 * <p>
 * Example
 * <p>
 * mysql&gt; CALL sys.ps_setup_save(-1);
 * Query OK, 0 rows affected (0.08 sec)
 * <p>
 * mysql&gt; UPDATE performance_schema.setup_instruments
 * -&gt;    SET enabled = 'YES', timed = 'YES';
 * Query OK, 547 rows affected (0.40 sec)
 * Rows matched: 784  Changed: 547  Warnings: 0
 * <p>
 * / * Run some tests that need more detailed instrumentation here * /
 * <p>
 * mysql&gt; CALL sys.ps_setup_reload_saved();
 * Query OK, 0 rows affected (0.32 sec)
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.2"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PsSetupSave extends AbstractRoutine<java.lang.Void> {

    /**
     * The parameter <code>sys.ps_setup_save.in_timeout</code>.
     */
    public static final Parameter<Integer> IN_TIMEOUT = createParameter("in_timeout", org.jooq.impl.SQLDataType.INTEGER, false, false);
    private static final long serialVersionUID = -136778697;

    /**
     * Create a new routine call instance
     */
    public PsSetupSave() {
        super("ps_setup_save", Sys.SYS);

        addInParameter(IN_TIMEOUT);
    }

    /**
     * Set the <code>in_timeout</code> parameter IN value to the routine
     */
    public void setInTimeout(Integer value) {
        setValue(IN_TIMEOUT, value);
    }
}
