/*
 * This file is generated by jOOQ.
 */
package jooq.sys.routines;


import jooq.sys.Sys;
import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;

import javax.annotation.Generated;


/**
 * Description
 * <p>
 * Takes an unquoted identifier (schema name, table name, etc.) and
 * returns the identifier quoted with backticks.
 * <p>
 * Parameters
 * <p>
 * in_identifier (TEXT):
 * The identifier to quote.
 * <p>
 * Returns
 * <p>
 * TEXT
 * <p>
 * Example
 * <p>
 * mysql&gt; SELECT sys.quote_identifier('my_identifier') AS Identifier;
 * +-----------------+
 * | Identifier      |
 * +-----------------+
 * | `my_identifier` |
 * +-----------------+
 * 1 row in set (0.00 sec)
 * <p>
 * mysql&gt; SELECT sys.quote_identifier('my`idenfier') AS Identifier;
 * +----------------+
 * | Identifier     |
 * +----------------+
 * | `my``idenfier` |
 * +----------------+
 * 1 row in set (0.00 sec)
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.2"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class QuoteIdentifier extends AbstractRoutine<String> {

    /**
     * The parameter <code>sys.quote_identifier.RETURN_VALUE</code>.
     */
    public static final Parameter<String> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.CLOB, false, false);
    /**
     * The parameter <code>sys.quote_identifier.in_identifier</code>.
     */
    public static final Parameter<String> IN_IDENTIFIER = createParameter("in_identifier", org.jooq.impl.SQLDataType.CLOB, false, false);
    private static final long serialVersionUID = 853404959;

    /**
     * Create a new routine call instance
     */
    public QuoteIdentifier() {
        super("quote_identifier", Sys.SYS, org.jooq.impl.SQLDataType.CLOB);

        setReturnParameter(RETURN_VALUE);
        addInParameter(IN_IDENTIFIER);
    }

    /**
     * Set the <code>in_identifier</code> parameter IN value to the routine
     */
    public void setInIdentifier(String value) {
        setValue(IN_IDENTIFIER, value);
    }

    /**
     * Set the <code>in_identifier</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setInIdentifier(Field<String> field) {
        setField(IN_IDENTIFIER, field);
    }
}
