/*
 * This file is generated by jOOQ.
 */
package jooq.sys.routines;


import jooq.sys.Sys;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.types.UByte;

import javax.annotation.Generated;


/**
 * Description
 * <p>
 * Returns the patch release version of MySQL Server.
 * <p>
 * Returns
 * <p>
 * TINYINT UNSIGNED
 * <p>
 * Example
 * <p>
 * mysql&gt; SELECT VERSION(), sys.version_patch();
 * +--------------------------------------+---------------------+
 * | VERSION()                            | sys.version_patch() |
 * +--------------------------------------+---------------------+
 * | 5.7.9-enterprise-commercial-advanced | 9                   |
 * +--------------------------------------+---------------------+
 * 1 row in set (0.00 sec)
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.2"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class VersionPatch extends AbstractRoutine<UByte> {

    /**
     * The parameter <code>sys.version_patch.RETURN_VALUE</code>.
     */
    public static final Parameter<UByte> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.TINYINTUNSIGNED, false, false);
    private static final long serialVersionUID = 1076788477;

    /**
     * Create a new routine call instance
     */
    public VersionPatch() {
        super("version_patch", Sys.SYS, org.jooq.impl.SQLDataType.TINYINTUNSIGNED);

        setReturnParameter(RETURN_VALUE);
    }
}
