/*
 * This file is generated by jOOQ.
 */
package jooq.black_poker.tables.records;


import jooq.black_poker.tables.Inner;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.2"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class InnerRecord extends TableRecordImpl<InnerRecord> implements Record1<String> {

    private static final long serialVersionUID = 2075781040;

    /**
     * Create a detached InnerRecord
     */
    public InnerRecord() {
        super(Inner.INNER);
    }

    /**
     * Create a detached, initialised InnerRecord
     */
    public InnerRecord(String user) {
        super(Inner.INNER);

        set(0, user);
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>black_poker.inner.user</code>.
     */
    public String getUser() {
        return (String) get(0);
    }

    /**
     * Setter for <code>black_poker.inner.user</code>.
     */
    public void setUser(String value) {
        set(0, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Inner.INNER.USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUser();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public InnerRecord value1(String value) {
        setUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InnerRecord values(String value1) {
        value1(value1);
        return this;
    }
}
