/*
 * This file is generated by jOOQ.
 */
package jooq.black_poker;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.DefaultCatalog;
import jooq.black_poker.tables.Inner;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BlackPoker extends SchemaImpl {

    private static final long serialVersionUID = -391389042;

    /**
     * The reference instance of <code>black_poker</code>
     */
    public static final BlackPoker BLACK_POKER = new BlackPoker();

    /**
     * The table <code>black_poker.inner</code>.
     */
    public final Inner INNER = jooq.black_poker.tables.Inner.INNER;

    /**
     * No further instances allowed
     */
    private BlackPoker() {
        super("black_poker", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Inner.INNER);
    }
}
