/*
 * This file is generated by jOOQ.
 */
package jooq.black_poker;


import jooq.black_poker.tables.Inner;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in black_poker
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.2"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>black_poker.inner</code>.
     */
    public static final Inner INNER = jooq.black_poker.tables.Inner.INNER;
}
