/*
 * This file is generated by jOOQ.
 */
package jooq.scp_tcg;


import jooq.scp_tcg.tables.Deck;
import jooq.scp_tcg.tables.Id;
import jooq.scp_tcg.tables.records.DeckRecord;
import jooq.scp_tcg.tables.records.IdRecord;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>scp_tcg</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
            "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DeckRecord> KEY_DECK_PRIMARY = UniqueKeys0.KEY_DECK_PRIMARY;
    public static final UniqueKey<IdRecord> KEY_ID_PRIMARY = UniqueKeys0.KEY_ID_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<DeckRecord> KEY_DECK_PRIMARY = Internal.createUniqueKey(Deck.DECK, "KEY_deck_PRIMARY", Deck.DECK.ID, Deck.DECK.NAME);
        public static final UniqueKey<IdRecord> KEY_ID_PRIMARY = Internal.createUniqueKey(Id.ID, "KEY_id_PRIMARY", Id.ID.ID_);
    }
}
