/*
 * This file is generated by jOOQ.
 */
package jooq.scp_tcg;


import jooq.scp_tcg.tables.Deck;
import jooq.scp_tcg.tables.Id;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in scp_tcg
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.2"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>scp_tcg.deck</code>.
     */
    public static final Deck DECK = jooq.scp_tcg.tables.Deck.DECK;

    /**
     * The table <code>scp_tcg.id</code>.
     */
    public static final Id ID = jooq.scp_tcg.tables.Id.ID;
}
