/*
 * This file is generated by jOOQ.
 */
package jooq.sys.tables.records;


import jooq.sys.tables.X$memoryGlobalTotal;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;

import javax.annotation.Generated;
import java.math.BigInteger;


/**
 * VIEW
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.2"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class X$memoryGlobalTotalRecord extends TableRecordImpl<X$memoryGlobalTotalRecord> implements Record1<BigInteger> {

    private static final long serialVersionUID = 212514171;

    /**
     * Create a detached X$memoryGlobalTotalRecord
     */
    public X$memoryGlobalTotalRecord() {
        super(X$memoryGlobalTotal.X$MEMORY_GLOBAL_TOTAL);
    }

    /**
     * Create a detached, initialised X$memoryGlobalTotalRecord
     */
    public X$memoryGlobalTotalRecord(BigInteger totalAllocated) {
        super(X$memoryGlobalTotal.X$MEMORY_GLOBAL_TOTAL);

        set(0, totalAllocated);
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>sys.x$memory_global_total.total_allocated</code>.
     */
    public BigInteger getTotalAllocated() {
        return (BigInteger) get(0);
    }

    /**
     * Setter for <code>sys.x$memory_global_total.total_allocated</code>.
     */
    public void setTotalAllocated(BigInteger value) {
        set(0, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<BigInteger> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<BigInteger> valuesRow() {
        return (Row1) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigInteger> field1() {
        return X$memoryGlobalTotal.X$MEMORY_GLOBAL_TOTAL.TOTAL_ALLOCATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger component1() {
        return getTotalAllocated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger value1() {
        return getTotalAllocated();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public X$memoryGlobalTotalRecord value1(BigInteger value) {
        setTotalAllocated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public X$memoryGlobalTotalRecord values(BigInteger value1) {
        value1(value1);
        return this;
    }
}
