/*
 * This file is generated by jOOQ.
 */
package jooq.mysql;


import javax.annotation.Generated;

import jooq.mysql.tables.ColumnsPriv;
import jooq.mysql.tables.Db;
import jooq.mysql.tables.EngineCost;
import jooq.mysql.tables.Event;
import jooq.mysql.tables.Func;
import jooq.mysql.tables.GeneralLog;
import jooq.mysql.tables.GtidExecuted;
import jooq.mysql.tables.HelpCategory;
import jooq.mysql.tables.HelpKeyword;
import jooq.mysql.tables.HelpRelation;
import jooq.mysql.tables.HelpTopic;
import jooq.mysql.tables.InnodbIndexStats;
import jooq.mysql.tables.InnodbTableStats;
import jooq.mysql.tables.NdbBinlogIndex;
import jooq.mysql.tables.Plugin;
import jooq.mysql.tables.Proc;
import jooq.mysql.tables.ProcsPriv;
import jooq.mysql.tables.ProxiesPriv;
import jooq.mysql.tables.ServerCost;
import jooq.mysql.tables.Servers;
import jooq.mysql.tables.SlaveMasterInfo;
import jooq.mysql.tables.SlaveRelayLogInfo;
import jooq.mysql.tables.SlaveWorkerInfo;
import jooq.mysql.tables.SlowLog;
import jooq.mysql.tables.TablesPriv;
import jooq.mysql.tables.TimeZone;
import jooq.mysql.tables.TimeZoneLeapSecond;
import jooq.mysql.tables.TimeZoneName;
import jooq.mysql.tables.TimeZoneTransition;
import jooq.mysql.tables.TimeZoneTransitionType;
import jooq.mysql.tables.User;


/**
 * Convenience access to all tables in mysql
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Column privileges
     */
    public static final ColumnsPriv COLUMNS_PRIV = jooq.mysql.tables.ColumnsPriv.COLUMNS_PRIV;

    /**
     * Database privileges
     */
    public static final Db DB = jooq.mysql.tables.Db.DB;

    /**
     * The table <code>mysql.engine_cost</code>.
     */
    public static final EngineCost ENGINE_COST = jooq.mysql.tables.EngineCost.ENGINE_COST;

    /**
     * Events
     */
    public static final Event EVENT = jooq.mysql.tables.Event.EVENT;

    /**
     * User defined functions
     */
    public static final Func FUNC = jooq.mysql.tables.Func.FUNC;

    /**
     * General log
     */
    public static final GeneralLog GENERAL_LOG = jooq.mysql.tables.GeneralLog.GENERAL_LOG;

    /**
     * The table <code>mysql.gtid_executed</code>.
     */
    public static final GtidExecuted GTID_EXECUTED = jooq.mysql.tables.GtidExecuted.GTID_EXECUTED;

    /**
     * help categories
     */
    public static final HelpCategory HELP_CATEGORY = jooq.mysql.tables.HelpCategory.HELP_CATEGORY;

    /**
     * help keywords
     */
    public static final HelpKeyword HELP_KEYWORD = jooq.mysql.tables.HelpKeyword.HELP_KEYWORD;

    /**
     * keyword-topic relation
     */
    public static final HelpRelation HELP_RELATION = jooq.mysql.tables.HelpRelation.HELP_RELATION;

    /**
     * help topics
     */
    public static final HelpTopic HELP_TOPIC = jooq.mysql.tables.HelpTopic.HELP_TOPIC;

    /**
     * The table <code>mysql.innodb_index_stats</code>.
     */
    public static final InnodbIndexStats INNODB_INDEX_STATS = jooq.mysql.tables.InnodbIndexStats.INNODB_INDEX_STATS;

    /**
     * The table <code>mysql.innodb_table_stats</code>.
     */
    public static final InnodbTableStats INNODB_TABLE_STATS = jooq.mysql.tables.InnodbTableStats.INNODB_TABLE_STATS;

    /**
     * The table <code>mysql.ndb_binlog_index</code>.
     */
    public static final NdbBinlogIndex NDB_BINLOG_INDEX = jooq.mysql.tables.NdbBinlogIndex.NDB_BINLOG_INDEX;

    /**
     * MySQL plugins
     */
    public static final Plugin PLUGIN = jooq.mysql.tables.Plugin.PLUGIN;

    /**
     * Stored Procedures
     */
    public static final Proc PROC = jooq.mysql.tables.Proc.PROC;

    /**
     * Procedure privileges
     */
    public static final ProcsPriv PROCS_PRIV = jooq.mysql.tables.ProcsPriv.PROCS_PRIV;

    /**
     * User proxy privileges
     */
    public static final ProxiesPriv PROXIES_PRIV = jooq.mysql.tables.ProxiesPriv.PROXIES_PRIV;

    /**
     * MySQL Foreign Servers table
     */
    public static final Servers SERVERS = jooq.mysql.tables.Servers.SERVERS;

    /**
     * The table <code>mysql.server_cost</code>.
     */
    public static final ServerCost SERVER_COST = jooq.mysql.tables.ServerCost.SERVER_COST;

    /**
     * Master Information
     */
    public static final SlaveMasterInfo SLAVE_MASTER_INFO = jooq.mysql.tables.SlaveMasterInfo.SLAVE_MASTER_INFO;

    /**
     * Relay Log Information
     */
    public static final SlaveRelayLogInfo SLAVE_RELAY_LOG_INFO = jooq.mysql.tables.SlaveRelayLogInfo.SLAVE_RELAY_LOG_INFO;

    /**
     * Worker Information
     */
    public static final SlaveWorkerInfo SLAVE_WORKER_INFO = jooq.mysql.tables.SlaveWorkerInfo.SLAVE_WORKER_INFO;

    /**
     * Slow log
     */
    public static final SlowLog SLOW_LOG = jooq.mysql.tables.SlowLog.SLOW_LOG;

    /**
     * Table privileges
     */
    public static final TablesPriv TABLES_PRIV = jooq.mysql.tables.TablesPriv.TABLES_PRIV;

    /**
     * Time zones
     */
    public static final TimeZone TIME_ZONE = jooq.mysql.tables.TimeZone.TIME_ZONE;

    /**
     * Leap seconds information for time zones
     */
    public static final TimeZoneLeapSecond TIME_ZONE_LEAP_SECOND = jooq.mysql.tables.TimeZoneLeapSecond.TIME_ZONE_LEAP_SECOND;

    /**
     * Time zone names
     */
    public static final TimeZoneName TIME_ZONE_NAME = jooq.mysql.tables.TimeZoneName.TIME_ZONE_NAME;

    /**
     * Time zone transitions
     */
    public static final TimeZoneTransition TIME_ZONE_TRANSITION = jooq.mysql.tables.TimeZoneTransition.TIME_ZONE_TRANSITION;

    /**
     * Time zone transition types
     */
    public static final TimeZoneTransitionType TIME_ZONE_TRANSITION_TYPE = jooq.mysql.tables.TimeZoneTransitionType.TIME_ZONE_TRANSITION_TYPE;

    /**
     * Users and global privileges
     */
    public static final User USER = jooq.mysql.tables.User.USER;
}
